### ISSUE TITLE
Error while installing dependencies

### ISSUE THREAD

**Issue by ferby09** [fabieu/sureflap-api#1]
Hi,
when trying to install the dependencies I get the following errors:
`pip install -r requirements.txt`
`Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 330, in run
    wheel_cache
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 295, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "/usr/lib/python2.7/dist-packages/pip/req/req_file.py", line 84, in parse_requirements
    filename, comes_from=comes_from, session=session
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 422, in get_file_content
    content = auto_decode(f.read())
  File "/usr/lib/python2.7/dist-packages/pip/utils/encoding.py", line 25, in auto_decode
    return data[len(bom):].decode(encoding)
  File "/usr/lib/python2.7/encodings/utf_16.py", line 16, in decode
    return codecs.utf_16_decode(input, errors, True)
UnicodeDecodeError: 'utf16' codec can't decode byte 0x0d in position 702: truncated data`
Additionally I got the following message beforehand:
`Could not find a version that satisfies the requirement cachetools==4.1.1 (from -r requirements.txt (line 1)) (from versions: 0.0.0, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 0.5.0, 0.5.1, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 2.0.0, 2.0.1, 2.1.0, 3.0.0, 3.1.0, 3.1.1)
No matching distribution found for cachetools==4.1.1 (from -r requirements.txt (line 1))`
I've changed it to 3.1.1 in requirements.txt.
I'm using Python 3.5.3-1 on a RPi3 with Raspbian Stretch. My goal is creating a module for my MagicMirror that simply displays the current location of my cat (indoor/outdoor).

**Comment by fabieu** [comment]
Hey ferby09,

first of all thank you for reaching out. I successfully replicated your issue and it seems like that the minimum required version for this project to run is Python 3.6 or higher. I recommend using at least Python 3.7 or newer, because this project was build with Python 3.7. Unfortunatly I can't give you any advise on how to modify the requirements, that they will work with an older version of Python. Probably not the answer you want to hear, but i dont have the time to ensure backwards compability.
Have a nice day!

**Comment by fabieu** [comment]
Hey ferby09,

first of all thanks for reaching out. I was able to replicate your issue and it seems that the pinned versions in the _requirements.txt_ are causing the issues. Later this day I will provide a fix for this by providing a _**Pipfile**_ instead of a _requirements.txt_ . 

It also seems you are using Python 2.7 instead of Python 3.5.3. You can check this by running `python --version` on your console. You can try using `python3 -m pip install -r requirements.txt` to force the installation of the packages via your configured Python 3 version.

If your problems persist feel free to reply. Have a nice day!

**Comment by ferby09** [comment]
Thank you for your help and rework of the project!
I'm fairly just a happy user but I did manage to install a working version of Python 3.6.2 after more recent versions (3.7 and 3.9) couldn't install the ssl module and the fix only worked for 3.6.
Anyway, after removing the other versions and successfully installing pipenv I've installed the project but pipenv couldn't find flask 2.0.1 for installation. I've installed it manually 
`python3.6 -m pip install flask`
and it's working now.
`python3.6 -m pipenv install     Creating a virtualenv for this project...                                Pipfile: /home/pi/sureflap/sureflap-api/Pipfile
Using /usr/local/bin/python3.6m (3.6.2) to create virtualenv...
⠦ Creating virtual environment...created virtual environment CPython3.6.2.final.0-32 in 24503ms
  creator CPython3Posix(dest=/home/pi/.local/share/virtualenvs/sureflap-api-7Z6lz6Pi, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/pi/.local/share/virtualenv)
    added seed packages: pip==21.1.3, setuptools==57.1.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment!                              Virtualenv location: /home/pi/.local/share/virtualenvs/sureflap-api-7Z6lz6Pi
Installing dependencies from Pipfile.lock (91e927)...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Ignoring colorama: markers 'platform_system == "Windows"' don't match your environment
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Ignoring pywin32: markers 'python_version < "3.10" and sys_platform == "win32" and implementation_name == "cpython"' don't match your environment
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 29/29 — 00:06:45
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.`

However, when I try starting the server I get some errors:
` python3.6 -m pipenv run python server.py
Traceback (most recent call last):
  File "server.py", line 1, in <module>
    from flask import Flask, render_template, request, jsonify
  File "/home/pi/.local/share/virtualenvs/sureflap-api-7Z6lz6Pi/lib/python3.6/site-packages/flask/__init__.py", line 3, in <module>
    from werkzeug.exceptions import abort as abort
  File "/home/pi/.local/share/virtualenvs/sureflap-api-7Z6lz6Pi/lib/python3.6/site-packages/werkzeug/__init__.py", line 2, in <module>
    from .test import Client as Client
  File "/home/pi/.local/share/virtualenvs/sureflap-api-7Z6lz6Pi/lib/python3.6/site-packages/werkzeug/test.py", line 30, in <module>
    from .sansio.multipart import Data
  File "/home/pi/.local/share/virtualenvs/sureflap-api-7Z6lz6Pi/lib/python3.6/site-packages/werkzeug/sansio/multipart.py", line 2, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'`

**Comment by fabieu** [comment]
You get errors because pipenv creates a virtual python environment with a dedicated Python Interpreter, which means you can't just install Flask with `python3.6 -m pip install flask`. It will be still missing in the virtualenv To install additional packages you have to navigate in the project directory and run `pipenv install Flask`. 

Why should new lines be a problem at all?

**Comment by ferby09** [comment]
Alright, I've installed flask as you mentioned. 
Resources was still missing so installed that as well. 
The server is starting now! I'll try some requests later but it seems like it's working.
Thank you very much for your help!

Regarding the empty lines: I was still talking about the code tags. If you have an empty line in there, it won't be recognized it seems.

`test
test`

`test

test`

**Comment by fabieu** [comment]
Ah, now I understand. For multi-line code you have to use triple apostroph, followed by a new line. For example:
\`\`\`bash
{your code here}
\`\`\`
