### ISSUE TITLE
SwaggerUI TypeError: Failed to fetch

### ISSUE THREAD

**Issue by ferby09** [fabieu/sureflap-api#2]
Hi again,
I've set up the server and can access the SwaggerUI with http://xxx.xxx.xxx.xxx:2311
However, I didn't manage to run it via pm2. That may be because I have to use `python3.6 -m pipenv run python server.py` to run it. 
So, `pm2 start python3.6 -m pipenv run python server.py --watch --name SureFlap_API` doesn't seem to work. It gets added but I can't access the UI.

Apart from that problem, when I start the server manually I can access the UI but if I'm using the "Try it out"-feature it returns 

CURL
`curl -X GET "http://localhost:3001/households" -H  "accept: application/json"`
Request URL
`http://localhost:3001/households`
Code
`TypeError: Failed to fetch`

Thank you very much for your help so far!

**Comment by fabieu** [comment]
Hey ferby09,
sometimes using PM2 with virtual environments can be tricky, so I don't know if the proposed solution is working for you. Can you try out the two following commands to spawn a new PM2 process. 
```
python3.6 -m pipenv shell
pm2 start python3.6 server.py --watch --name SureFlap_API --restart-delay 1000
(pm2 start python server.py --watch --name SureFlap_API --restart-delay 1000)
```
Essentialy what these do, is that the first command creates a new shell session in the virtual environment while the second one is using the current session for creating the PM2 process. PM2 is smart enough to detects its running in a virtual environment and saves the environment to the process daemon.

The error with SwaggerUI is fairly simple. Because the SwaggerUI configuration is static i had to pick an url for its request, which is `http://localhost:3001`. But your server is running on port 2311 as specifiec in the `config.ini` file. So either changing the port in `openapi.yaml` from 3001 to 2311 or chaning the port in the `config.ini` from 2311 to 3001 will resolve the issue. I messed up the default port in the _config.ini.sample_, which I changed later to 3001. I recommend changing it there hence it is easier to find.

**Comment by ferby09** [comment]
Your proposal for PM2 works like a charm!

I've noticed the wrong port as well and already tried changing it to 3001. Did that again just now but the problem persists.

**Comment by fabieu** [comment]
Am I right in assuming, that you try to access the SwaggerUI from a different system than it is running on?
In this case you need to edit the **servers** configuration in the `openapi.yaml` specification (Path: /static/specs/openapi.yaml) on line 12 to the IP or hostname of your RPi. SwaggerUI just constructs the API calls and sends them to the specified servers url from your local browser. 

If the issue persists. please post the output of the console in the developer tools of your browser.

**Comment by ferby09** [comment]
Nice, everything works now!
Now I just need to implement it into a MagicMirror module but that shouldn't be difficult.
Thank you so much for your help!
Or in German: Ich küsse deine Augen!
